### ISSUE TITLE
Is there a "list users" method ? 

### ISSUE THREAD

**Issue by brucellino** [csgf/glibrary#5]
Hello friendly devs.

I've got an Ansible playbook which takes care of user and repo creation. However, the API throws a 422 when I create an exisiting user (see below). Now, I could accept 422 as a valid success code, but I'd like to avoid making unnecessary requests, by getting a list of users and then checking if mine are in the list.

Is there a method for getting the full list of users ?

```javascript
failed:[  
   sgw-dev.sci-gaia.eu
](item={  
   u'github':{  
      u'username':u'yosephabate',
      u'confirmed':True
   },
   u'name':u'Yoseph Abate',
   u'institute':None,
   u'twitter':None,
   u'orcid':u'0000-0001-5098-2063',
   u'homepage':   u'http://itsc.aait.edu.et',
   u'email':u'yosjudea@yahoo.com'
}) =>{  
   "access_control_allow_credentials":"true",
   "connection":"close",
   "content":"{\"error\":{\"name\":\"ValidationError\",\"status\":422,\"message\":\"The `user` instance is not valid. Details: `username` User already exists (value: \\\"yosephabate\\\"); `email` Email already exists (value: \\\"yosjudea@yahoo.com\\\").\",\"statusCode\":422,\"details\":{\"context\":\"user\",\"codes\":{\"username\":[\"uniqueness\"],\"email\":[\"uniqueness\"]},\"messages\":{\"username\":[\"User already exists\"],\"email\":[\"Email already exists\"]}},\"stack\":\"ValidationError: The `user` instance is not valid. Details: `username` User already exists (value: \\\"yosephabate\\\"); `email` Email already exists (value: \\\"yosjudea@yahoo.com\\\").\\n    at /home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/dao.js:317:12\\n    at ModelConstructor.<anonymous> (/home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/validations.js:487:13)\\n    at ModelConstructor.next (/home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/hooks.js:75:12)\\n    at done (/home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/validations.js:484:25)\\n    at /home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/validations.js:558:7\\n    at ModelConstructor.<anonymous> (/home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/validations.js:357:5)\\n    at /home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/dao.js:1561:9\\n    at done (/home/adimariano/glibrary/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:167:19)\\n    at /home/adimariano/glibrary/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16\\n    at /home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/dao.js:1545:13\"}}",
   "content_length":"1701",
   "content_type":"application/json; charset=utf-8",
   "date":"Mon, 28 Nov 2016 08:45:07 GMT",
   "etag":"W/\"6a5-YvBiuSF+kClAQMkEQ/t4cw\"",
   "failed":true,
   "item":{  
      "email":"yosjudea@yahoo.com",
      "github":{  
         "confirmed":true,
         "username":"yosephabate"
      },
      "homepage":"http://itsc.aait.edu.et",
      "institute":null,
      "name":"Yoseph Abate",
      "orcid":"0000-0001-5098-2063",
      "twitter":null
   },
   "json":{  
      "error":{  
         "details":{  
            "codes":{  
               "email":[  
                  "uniqueness"
               ],
               "username":[  
                  "uniqueness"
               ]
            },
            "context":"user",
            "messages":{  
               "email":[  
                  "Email already exists"
               ],
               "username":[  
                  "User already exists"
               ]
            }
         },
         "message":"The `user` instance is not valid. Details: `username` User already exists (value: \"yosephabate\"); `email` Email already exists (value: \"yosjudea@yahoo.com\").",
         "name":"ValidationError",
         "stack":"ValidationError: The `user` instance is not valid. Details: `username` User already exists (value: \"yosephabate\"); `email` Email already exists (value: \"yosjudea@yahoo.com\").\n    at /home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/dao.js:317:12\n    at ModelConstructor.<anonymous> (/home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/validations.js:487:13)\n    at ModelConstructor.next (/home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/hooks.js:75:12)\n    at done (/home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/validations.js:484:25)\n    at /home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/validations.js:558:7\n    at ModelConstructor.<anonymous> (/home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/validations.js:357:5)\n    at /home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/dao.js:1561:9\n    at done (/home/adimariano/glibrary/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:167:19)\n    at /home/adimariano/glibrary/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16\n    at /home/adimariano/glibrary/node_modules/loopback-datasource-juggler/lib/dao.js:1545:13",
         "status":422,
         "statusCode":422
      }
   },
   "msg":"Status code was not [200]: HTTP Error 422: Unprocessable Entity",
   "redirected":false,
   "status":422,
   "url":"https://glibrary.ct.infn.it:3500/v2/users",
   "vary":"Origin, Accept-Encoding",
   "x_powered_by":"Express"
}
```

**Comment by brucellino** [comment]
Ok, I've found out that there was a problem with the permissions of the user I was using to manage the other things (users and repos). The "list users" method is working fine and it's at `/v2/users`

Closing this.
